---
namespace: bookinfo
bases:
- ../../base
patchesJson6902:
  - target:
      version: v1
      kind: Namespace
      name: mesh-member-1
    patch: |-
      - op: replace
        path: /metadata/name
        value: bookinfo
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: api-endpoint
    patch: |-
      - op: add
        path: /spec/template/metadata/annotations
        value:
          sidecar.istio.io/inject: "true"
...
