apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: api-endpoint
    app.openshift.io/runtime: quarkus
  name: api-endpoint
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: api-endpoint
  strategy:
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: api-endpoint
    spec:
      affinity:
        podAntiAffinity:
          preferedDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - api-endpoint
              topologyKey: kubernetes.io/hostname
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: QUARKUS_OPTS
          value: -Dquarkus.http.host=0.0.0.0
        - name: QUARKUS_HOME
          value: /home/quarkus/
        image: quay.io/jaeichle/api-endpoint:latest@sha256:cc3778ea4b6d61d755ddcb266c3c546b3b194876e3a08ef471f40bf534d5e464
        imagePullPolicy: IfNotPresent
        name: api-endpoint
        ports:
        - containerPort: 9080
          name: http
          protocol: TCP
        resources:
          requests:
            memory: "64Mi"
            cpu: "25m"
          limits:
            memory: "256Mi"
            cpu: "100m"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccountName: api-endpoint
      serviceAccount: api-endpoint
      terminationGracePeriodSeconds: 30
