name: build and push

on:
  push:
    branches:
      - main
    paths-ignore:
      - "deployment/**"
      - ".github/worflows/**"
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0' # weekly

jobs:
  build-and-push-latest:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3.5.2
    - name: Build Image with Buildah
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: api-endpoint
        tags: latest ${{ github.sha }}
        containerfiles: |
          ./src/main/docker/Dockerfile.native-distroless
        context: .
    - name: Push to quay.io
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags: ${{ steps.build-image.outputs.tags }}
        registry: quay.io/jaeichle
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
