name: run unit tests

on:
  pull_request:
    branches:
    - main
    paths-ignore:
      - "deployment/**"
      - ".github/workflows/**"
      - "src/main/docker/Dockerfile"
      - "src/main/docker/Dockerfile.native-distroless"
      - ".gitignore"
      - ".dockerignore"
      - "README.md"

jobs:
  pass-unit-tests:

    runs-on: ubuntu-latest

    steps:
    - name: Install JDK17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Repository checkout
      uses: actions/checkout@v3

    - name: Run native integration tests
      run: |
        ./mvnw -e -B clean verify --fail-at-end -Dnative -Dstart-containers \
        -Dquarkus.native.container-build=true -am -Dquarkus.test.integration-test-profile=test