name: run unit tests

on:
  pull_request:
    branches:
    - main

jobs:
  pass-unit-tests:

    runs-on: ubuntu-latest

    steps:
    - name: Install JDK17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Repository checkout
      uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

    - name: Run native integration tests
      run: |
        ./mvnw -e -B clean verify --fail-at-end -Dnative -Dstart-containers \
        -Dquarkus.native.container-build=true -am -Dquarkus.test.integration-test-profile=test